### ISSUE TITLE
Tekla 2022 sp4 - app is not running

### ISSUE THREAD

**Issue by StupidAI** [karpovichpv/Lookup#1]
Windows 10 x64 (build 19041). Tekla 2022 Service Pack 4 (Build 18156). Copy files .exe and .dll to C:\ProgramData\Trimble\Tekla Structures\2022.0\Environments\common\extensions. Copy files .cs and .bmp to C:\ProgramData\Trimble\Tekla Structures\2022.0\Environments\common\macros\drawings, C:\ProgramData\Trimble\Tekla Structures\2022.0\Environments\common\macros\modeling. And when I try to run app nothing is happend. Checked on 2 PCs.

**Comment by karpovichpv** [comment]
Hello @StupidAI, try to install a tsep file -  https://github.com/karpovichpv/Lookup/releases/tag/v.0.5
