### ISSUE TITLE
Неверный путь установки макроса для вызова на чертежах

### ISSUE THREAD

**Issue by ivanharlanov** [karpovichpv/Lookup#4]
Выделенную папку ("drawing") создает TSEP:
![image](https://github.com/karpovichpv/Lookup/assets/109338918/17b58724-fa52-4766-8d5d-b939bbcfd52e)
А должен закидывать макрос и .bmp в папку ниже, т.е. "drawings"

**Comment by karpovichpv** [comment]
Исправлено в версии 2.0
